DEBUG:root:received {"dest":"n1","body":{"type":"init","node_id":"n1","node_ids":["n0","n1","n2","n3"],"msg_id":1},"src":"c1","id":1}
INFO:root:node n1 initialized
DEBUG:root:sending {"dest": "c1", "src": "n1", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n1","body":{"txn":[["append",9,1],["append",9,2]],"type":"txn","msg_id":1},"src":"c10","id":12}
INFO:root:executing txn
DEBUG:root:c10-1: locking 9
INFO:root:CTX 
namespace(tid='c10-1', locked=[9])
 msg id1
INFO:root:c10-1: aborted
DEBUG:root:sending {"dest": "c10", "src": "n1", "body": {"msg_id": 2, "in_reply_to": 1, "type": "error", "code": 14, "text": "transaction aborted"}}
DEBUG:root:c10-1: unlocking 9
DEBUG:root:received {"dest":"n1","body":{"txn":[["append",7,3],["append",9,3],["append",9,4]],"type":"txn","msg_id":2},"src":"c10","id":19}
INFO:root:executing txn
DEBUG:root:c10-2: locking 7
DEBUG:root:c10-2: locking 9
INFO:root:CTX 
namespace(tid='c10-2', locked=[7, 9])
 msg id2
DEBUG:root:c10-2: appending to 7: 3
DEBUG:root:c10-2: appending to 9: 3
DEBUG:root:c10-2: appending to 9: 4
DEBUG:root:c10-2: updating 7: [3]
DEBUG:root:c10-2: updating 9: [3, 4]
DEBUG:root:sending {"dest": "c10", "src": "n1", "body": {"msg_id": 3, "in_reply_to": 2, "type": "txn_ok", "txn": [["append", 7, 3], ["append", 9, 3], ["append", 9, 4]]}}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-4' coro=<handle() done, defined at /home/peter/Documents/tf/lab4/cent.py:15> exception=TypeError("'types.SimpleNamespace' object is not callable")>
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab4/cent.py", line 39, in handle
    msg(node, type='txnRep',txn=msg.body.txn, originalid=msg.body.msg_id)
TypeError: 'types.SimpleNamespace' object is not callable
DEBUG:root:received {"dest":"n1","body":{"txn":[["append",9,7],["append",8,2],["append",9,8],["r",8,null]],"type":"txn","msg_id":3},"src":"c10","id":25}
INFO:root:executing txn
DEBUG:root:c10-3: locking 8
DEBUG:root:c10-3: locking 9
