DEBUG:root:received {"dest":"n2","body":{"type":"init","node_id":"n2","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c3","id":3}
INFO:root:node n2 initialized
DEBUG:root:sending {"dest": "c3", "src": "n2", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n2","src":"n1","body":{"msg_id":2,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[[["pass",null],0]],"commit":0},"id":10}
DEBUG:root:sending {"dest": "n1", "src": "n2", "body": {"msg_id": 2, "in_reply_to": 2, "type": "AppendEntriesRes", "res": true, "term": 0, "next": 2, "commit": 0}}
DEBUG:root:received {"dest":"n2","src":"n1","body":{"msg_id":6,"type":"AppendEntries","term":0,"prevIndex":1,"prevTerm":[0,[3,2]],"entries":[["write",[1,1],0]],"commit":0},"id":20}
DEBUG:root:sending {"dest": "n1", "src": "n2", "body": {"msg_id": 3, "in_reply_to": 6, "type": "AppendEntriesRes", "res": false, "term": 0}}
DEBUG:root:received {"dest":"n2","src":"n1","body":{"msg_id":10,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[["cas",[0,[3,2]],0],["write",[1,1],0]],"commit":0},"id":27}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 301, in handle
    buildString([ "301",log,msg.body.prevIndex,commitIndex,node_id,entry, log[msg.body.prevIndex+i],msg.body.entries[i-1],i ])
UnboundLocalError: local variable 'entry' referenced before assignment
