DEBUG:root:received {"dest":"n2","body":{"type":"init","node_id":"n2","node_ids":["n1","n2","n3","n4","n5"],"msg_id":1},"src":"c0","id":0}
INFO:root:node n2 initialized
DEBUG:root:sending {"dest": "c0", "src": "n2", "body": {"msg_id": 1, "in_reply_to": 1, "type": "init_ok"}}
DEBUG:root:received {"dest":"n2","src":"n1","body":{"msg_id":2,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[[["pass",null],0]],"commit":0},"id":10}
DEBUG:root:sending {"dest": "n1", "src": "n2", "body": {"msg_id": 2, "in_reply_to": 2, "type": "AppendEntriesRes", "res": true, "term": 0, "next": 2, "commit": 0}}
DEBUG:root:received {"dest":"n2","body":{"key":1,"from":3,"to":4,"type":"cas","msg_id":1},"src":"c14","id":28}
DEBUG:root:sending {"dest": "c14", "src": "n2", "body": {"msg_id": 3, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n2","body":{"key":1,"from":3,"to":0,"type":"cas","msg_id":1},"src":"c15","id":32}
DEBUG:root:sending {"dest": "c15", "src": "n2", "body": {"msg_id": 4, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n2","body":{"key":0,"from":4,"to":1,"type":"cas","msg_id":1},"src":"c16","id":34}
DEBUG:root:sending {"dest": "c16", "src": "n2", "body": {"msg_id": 5, "in_reply_to": 1, "type": "error", "code": 11, "text": "Not Leader"}}
DEBUG:root:received {"dest":"n2","src":"n1","body":{"msg_id":6,"type":"AppendEntries","term":0,"prevIndex":1,"prevTerm":[0,1],"entries":[["cas",[1,[4,2]],0]],"commit":0},"id":48}
DEBUG:root:sending {"dest": "n1", "src": "n2", "body": {"msg_id": 6, "in_reply_to": 6, "type": "AppendEntriesRes", "res": false, "term": 0}}
DEBUG:root:received {"dest":"n2","src":"n1","body":{"msg_id":10,"type":"AppendEntries","term":0,"prevIndex":0,"prevTerm":0,"entries":[["write",[0,1],0],["cas",[1,[4,2]],0]],"commit":0},"id":56}
ERROR:root:fatal exception in handler
Traceback (most recent call last):
  File "/home/peter/Documents/tf/lab3/ms.py", line 27, in exitOnError
    fn(*args)
  File "/home/peter/Documents/tf/lab3/raft.py", line 301, in handle
    buildString([ "301",log,msg.body.prevIndex,commitIndex,node_id, log[msg.body.prevIndex+i],msg.body.entries[i-1],i ])
  File "/home/peter/Documents/tf/lab3/raft.py", line 58, in buildString
    raise Exception(s)
Exception: 301
[(('pass', None), 0), [['pass', None], 0]]
0
0
n2
[['pass', None], 0]
['write', [0, 1], 0]
1

